### PR TITLE
Merge new updates

### PR DESCRIPTION
**Pull request by iychoi**
- Bugfix: segfault while checking the mount point
- Bugfix: segfault while processing program arguments #17 
- New feature; disable direct-io to support FileChannel in Java (NIO) #14

### CODE REVIEW

**Comment by trel** [comment]
This doesn't apply cleanly - can you rebase on master?

**Comment by iychoi** [comment]
I'll do soon.

**Comment by trel** [comment]
You could also force-push to the original branch and this PR will update automatically.

**Comment by iychoi** [comment]
I was able to make the tree clean.

**Pull request merged**
