### PR TITLE
Cache metadata (stat/dir)

### PR DESCRIPTION
**Pull request by iychoi**
Implement metadata cache
- Cache stat of a file/directory
- Cache directory entries
- Few minor performance optimizations related to metadata cache
- Make hard-coded parameters configurable via command-line options
- Refactor code

### CODE REVIEW

**Comment by trel** [comment]
A premature merge on my part, oops.

@iychoi, can you look at this again?

I'm seeing the following when building the merged tip of master:

```
ubuntu14:~/irods_client_fuse/build$ cmake ../
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/irods_client_fuse/build
ubuntu14:~/irods_client_fuse/build$ make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/irods_client_fuse/build
[  7%] Building CXX object CMakeFiles/irodsFs.dir/src/iFuse.BufferedFS.cpp.o
[ 15%] Building CXX object CMakeFiles/irodsFs.dir/src/iFuse.FS.cpp.o
/home/ubuntu/irods_client_fuse/src/iFuse.FS.cpp:1446:14: error: case value evaluates to 2148855297, which cannot be narrowed to type 'int' [-Wc++11-narrowing]
        case IFUSEIOC_SHOW_CONNECTIONS:
             ^
/home/ubuntu/irods_client_fuse/include/iFuse.FS.hpp:23:35: note: expanded from macro 'IFUSEIOC_SHOW_CONNECTIONS'
#define IFUSEIOC_SHOW_CONNECTIONS _IOR(IOCTL_APP_NUMBER, 1, iFuseFsConnReport_t)
                                  ^
/usr/include/asm-generic/ioctl.h:75:28: note: expanded from macro '_IOR'
#define _IOR(type,nr,size)      _IOC(_IOC_READ,(type),(nr),(_IOC_TYPECHECK(size)))
                                ^
/usr/include/asm-generic/ioctl.h:66:2: note: expanded from macro '_IOC'
        (((dir)  << _IOC_DIRSHIFT) | \
        ^
1 error generated.
make[2]: *** [CMakeFiles/irodsFs.dir/src/iFuse.FS.cpp.o] Error 1
make[1]: *** [CMakeFiles/irodsFs.dir/all] Error 2
make: *** [all] Error 2
```

We'd like to make sure the tests are green.  If this will take some time, I can revert until it gets tightened up.

**Comment by iychoi** [comment]
Sorry, I merged this code from the old build environment. I'll test it again.

**Comment by trel** [comment]
Thanks!

**Comment by iychoi** [comment]
Check out a new PR, #7

**Pull request merged**
